name: Portfolio Theme Updater

on:
  push:
    branches:
      - master
  workflow_dispatch:
    # manual run
    inputs:
      hugoVersion:
        description: "Hugo Version"
        required: false
        default: "0.92.2"

jobs:
  Build:
    name: Building Themes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Base Theme Repo
        uses: actions/checkout@v3
        
  Deploy:
    name: Deploy Hugo Website
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Production
    steps:
      - name: Checkout Hugo Website Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPO_TARGET }}
          token: ${{ secrets.REPO_TOKEN }}
          
      - name: Fetch  Theme
        run: git submodule update --init --recursive

      - name: Update Theme to Latest commit
        run: git submodule update --remote --merge

      - name: Setup Hugo v${{ github.event.inputs.hugoVersion }}
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "${{ github.event.inputs.hugoVersion }}"
          
      - name: Build Hugo
        run: hugo --gc --verbose --minify
        
      - name: Commit Change And Push
        run: |
          git config --local user.email "${{ secrets.REPO_GIT_CONFIG_EMAIL }}"
          git config --local user.name "${{ secrets.REPO_GIT_CONFIG_NAME }}"
          git add --all
          git commit -m 'chore: Update Latest Theme' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
